Update README.md
OAI/OpenAPI-Specification pull request #2319
Opened 2020-08-19 12:25 UTC by PoojaChandak

Observed a few changes. Suggesting the same. Kindly check.

2020-08-25 08:37 UTC, ioggstream requested changes
see comments

2020-08-25 08:37 UTC, ioggstream commented on README.md
> +The TSC holds weekly web conferences to review open pull requests and discuss open issues related to the evolving OpenAPI Specification. Participation in weekly calls and scheduled working sessions a
Participation ... *is* open

2020-08-25 08:41 UTC, PoojaChandak commented on README.md
> +The TSC holds weekly web conferences to review open pull requests and discuss open issues related to the evolving OpenAPI Specification. Participation in weekly calls and scheduled working sessions a
Made the change as per review comment.

2020-09-15 03:21 UTC, PoojaChandak commented
The changes are done. Kindly check. @ioggstream

2020-11-09 07:27 UTC, PoojaChandak commented
Gentle reminder. Kindly check.

2021-07-09 19:29 UTC, chrissy35 approved these changes

2021-11-18 17:59 UTC, darrelmiller commented
Thank you for your suggestions.  I believe some of these grammar suggestions are subjective and don't bring a significant amount of additional clarity.  If you could provide some further evidence of why the current words should be changed we would consider making the changes.  We will take any guidance you can provide and use it for future work in this area.

2022-03-10 17:55 UTC, closed without merging