Added wording to clarify scope of references
OAI/OpenAPI-Specification pull request #2435
Opened 2021-01-07 15:38 UTC by darrelmiller

Previous wording was ambiguous as to what a $ref could point to.  This PR adds text to be more precise.

2021-01-07 15:41 UTC, MikeRalphson requested changes

2021-01-07 15:41 UTC, MikeRalphson commented on versions/3.1.0.md
> +A simple object to allow referencing other objects in the OpenAPI document, internally and externally. The target of the reference must match the type required by the context of the reference. Target
```suggestion
A simple object to allow referencing other objects in the OpenAPI document, internally and externally. The target of the reference must match the type required by the context of the reference. Targets of a reference do not need to be contained in a components section and for external references, targets do not need to exist within a valid OpenAPI document. The validity of the target MUST be based on the context of the reference object.
```

2021-01-07 15:43 UTC, MikeRalphson commented
See also #1679 to see if we can remove any now-redundant wording or improve elsewhere.

2021-01-08 07:37 UTC, MikeRalphson approved these changes

2021-01-09 19:40 UTC, darrelmiller commented
@OAI/tsc   Can I get another sign off?

2021-01-12 22:26 UTC, webron commented on versions/3.1.0.md
> +A simple object to allow referencing other objects in the OpenAPI document, internally and externally. Targets of a reference do not need to be contained in a components section and for external refe
Should we stick to a single term here? We use `targets` and `referenced objects` to mean the same thing.

2021-01-14 17:14 UTC, darrelmiller commented on versions/3.1.0.md
> +A simple object to allow referencing other objects in the OpenAPI document, internally and externally. Targets of a reference do not need to be contained in a components section and for external refe
```suggestion
A simple object to allow referencing other objects in the OpenAPI document, internally and externally. Targets of a reference do not need to be contained in a components section and for external references, targets MAY exist within any compatible resource. Targets are subject to the same constraints as inline objects.
```

2021-01-14 17:15 UTC, merged