Fixes Inconsistent JSON spacing
OAI/OpenAPI-Specification pull request #2543
Opened 2021-04-16 01:52 UTC by ArishSultan

the whole document uses 2-space indentation but at some places, 4-space indentation is used which is not consistent with the others.

2021-04-17 04:59 UTC, ArishSultan commented
@MikeRalphson

2021-05-05 05:22 UTC, ArishSultan commented
just a ping, anyone here?

2021-05-05 08:21 UTC, MikeRalphson requested changes
Thanks, LGTM. There appears to be at least one case of a `json` code block being indented by 3 spaces (the first example for array formatting). Could you also fix that one?

2021-05-06 02:28 UTC, MikeRalphson approved these changes
LGTM now, thanks.

2021-05-27 16:53 UTC, webron commented
Thanks for the update!

2021-05-27 16:53 UTC, merged