Mutual TLS Sample
OAI/OpenAPI-Specification pull request #2625
Opened 2021-06-21 12:26 UTC by philsturgeon

2021-06-21 12:30 UTC, MikeRalphson commented
The `type` value is `mutualTLS` not `tls`.

2021-11-11 17:51 UTC, darrelmiller commented on versions/3.1.0.md
> +  "description": "Cert must be signed by evilcorp.com CA"
```suggestion
  "description": "Cert must be signed by example.com CA"
```

2021-11-11 17:52 UTC, darrelmiller requested changes
Hey Phil, please approve the new name.

2021-11-11 17:52 UTC, darrelmiller commented on versions/3.1.0.md
> +description: Cert must be signed by evilcorp.com CA
```suggestion
description: Cert must be signed by example.com CA
```

2021-11-12 11:17 UTC, philsturgeon commented
Done!

2021-11-18 17:28 UTC, darrelmiller approved these changes

2021-11-18 17:29 UTC, merged

2023-09-18 06:09 UTC, commonism commented
this was merged into versions/3.1.0.md in the v3.1.1-dev branch
I' expect it to be in versions/3.1.1.md and 3.2.0.md