minor simplification of v3.1 schema
OAI/OpenAPI-Specification pull request #2671
Opened 2021-08-06 21:31 UTC by karenetheridge

"if the X property is present, then apply this constraint to property X" can
be simplified by simply stating the constraint for property X.

2021-08-09 19:19 UTC, jdesrosiers requested changes
You're right, this doesn't work like I intended.

Would you mind also making a couple other corrections I noticed when reviewing?

1. The "allowEmptyValue" property doesn't apply to headers. That can be removed.
2. The schema doesn't include the constraint that one and only of "schema" or "content" is required.

2021-08-10 05:48 UTC, karenetheridge commented
yes, give me a day or two

2021-08-10 22:55 UTC, karenetheridge commented
> The "allowEmptyValue" property doesn't apply to headers. That can be removed.

Are you sure? https://spec.openapis.org/oas/v3.1.0#headerObject specifies that it's the same as parameter, except no 'name' or 'in' -- and 'parameter' has 'allowEmptyValue'.

> The schema doesn't include the constraint that one and only of "schema" or "content" is required.

done.

2021-08-10 22:58 UTC, karenetheridge commented
since the header definition has 'unevaluatedProperties: false' in it, does this mean that no one has been testing this schema yet against headers (or surely they would have noticed the allowEmptyValue discrepancy)??!

2021-08-11 21:40 UTC, jdesrosiers commented
> > The "allowEmptyValue" property doesn't apply to headers. That can be removed.
>
> Are you sure?

Sorry, I meant the "allowReserved" property doesn't apply to headers. :facepalm: 

I came to this conclusion because the `in` value is implicitly `header` and the `allowReserved` description says, "This property only applies to parameters with an `in` value of `query`." Therefore, I concluded that `allowReserved` doesn't apply to the Header Object.

Actually, now that I look at it again, it looks like the same is true of `allowEmptyValue`. It's description says, "This is valid only for `query` parameters". This is for a header parameter, so it doesn't apply either.

2021-08-12 16:56 UTC, jdesrosiers requested changes

2021-08-12 16:56 UTC, jdesrosiers commented on schemas/v3.1/schema.yaml
>              type: boolean
Let's remove this one too.
```suggestion
```

2021-08-12 18:18 UTC, karenetheridge commented on schemas/v3.1/schema.yaml
>              type: boolean
done.

2021-08-12 21:10 UTC, jdesrosiers approved these changes
Thanks!

2021-09-18 23:38 UTC, jdesrosiers approved these changes

2021-09-23 16:21 UTC, darrelmiller approved these changes

2021-09-23 16:22 UTC, merged