Add scopes as required field of OAuth Flow Object
OAI/OpenAPI-Specification pull request #2673
Opened 2021-08-10 17:13 UTC by char0n

This makes metaschema consistent with the 3.0.x spec.

Refs #2666

2021-08-10 23:39 UTC, karenetheridge requested changes
Please update schema.yaml as well.

2021-08-11 05:59 UTC, char0n commented
@karenetheridge schema.yaml is updated as well now.

2021-08-11 07:27 UTC, hkosova commented
Should the schema `id` also be updated to the current date?

```diff
-id: https://spec.openapis.org/oas/3.0/schema/2020-02-25
+id: https://spec.openapis.org/oas/3.0/schema/2021-08-10
```

This was done the last time when the 3.0 schema was updated:
https://github.com/OAI/OpenAPI-Specification/pull/2158/files

2021-08-11 18:20 UTC, webron commented
Update procedure is in the [README](https://github.com/OAI/OpenAPI-Specification/blob/main/schemas/v3.0/README.md) 😃

2021-08-11 18:52 UTC, webron commented
That was also a nudge to @MikeRalphson as he likes automating things ;) You can keep the json version too, I don't see it as a problem.

2021-08-12 06:35 UTC, char0n commented
Ok now it's done precisely according to the README ;]

2021-08-19 16:45 UTC, darrelmiller approved these changes

2021-08-19 16:47 UTC, merged