tighten up regexes for path items
OAI/OpenAPI-Specification pull request #2681
Opened 2021-08-23 23:33 UTC by karenetheridge

https://spec.openapis.org/oas/v3.1.0#pathTemplating
"The value for these path parameters MUST NOT contain any unescaped “generic syntax” characters described by [[!RFC3986]]: forward slashes (/), question marks (?), or hashes (#)."

2021-08-24 09:05 UTC, MikeRalphson requested changes

2021-08-24 09:05 UTC, MikeRalphson commented on schemas/v3.1/schema.json
> +        "^/[^#?]*$": {
As mentioned on Slack, I believe this restriction would be going beyond what the markdown source-of-truth dictates (solely that the path key MUST start with a forward slash). Though unescaped `#` and '?' characters cannot appear within path template variables, there is afaik no restriction on them occurring **outside** those parameters. I make no comment on whether that is fortunate or not.

2021-09-20 18:37 UTC, jdesrosiers commented
This looks good to me if @MikeRalphson confirms that it accurately reflects the specification.

2021-09-23 16:18 UTC, darrelmiller approved these changes

2021-09-27 22:58 UTC, merged