Concise Documentation for Better Understanding
OAI/OpenAPI-Specification pull request #2962
Opened 2022-07-02 19:52 UTC by amritpalsingh5191

2023-03-02 14:43 UTC, MikeRalphson requested changes

2023-03-02 14:43 UTC, MikeRalphson commented on README.md
> -The OpenAPI Specification (OAS) defines a standard, programming language-agnostic interface description for HTTP APIs, which allows both humans and computers to discover and understand the capabiliti
Can we omit this, as it may cause confusion as to what "properly" means in this context?

2023-05-05 08:07 UTC, MikeRalphson commented
Please could you resolve the merge conflicts?

2023-11-15 09:36 UTC, lornajane commented
Closing due to inactivity but please feel free to re-open with the conflicts resolved. You should also review the [development guidelines](https://github.com/OAI/OpenAPI-Specification/blob/main/DEVELOPMENT.md) and check which version/branch should be targeted with this PR since we don't accept changes directly to the main branch.

2023-11-15 09:36 UTC, closed without merging