Make links relative
OAI/OpenAPI-Specification pull request #3179
Opened 2023-03-01 17:50 UTC by handrews

This allows [renderings of forks](https://handrews.github.io/OpenAPI-Specification/) to work.  Otherwise the links all 404 because forks are rendered under a directory name.

2023-03-01 18:03 UTC, MikeRalphson commented
Thanks @handrews - are we sure this won't break the main site which is deployed without a directory name? I seem to recall I had difficulty making it work for both cases? Not that I hate jekyll or anything.

2023-03-01 18:33 UTC, handrews commented
@MikeRalphson I actually missed some links, the most recent commit should be correct (I could have sworn I tested those pages... blah).

There could be jekyll weirdness that might prevent this from working, I have no idea how to test it, though.  OpenAPI is using a custom domain, and I do not, so I don't know if that's a concern.

I can't think of any reason why it _wouldn't_ work, as the `./` should just go relative to the root, but... jekyll (I unabashedly hate jekyll).

2023-03-01 18:42 UTC, MikeRalphson commented
It looks like I set up https://spec.mermade.org.uk/ in the dim and distant past for testing, so will pull your changes. Thanks.

2023-03-02 15:24 UTC, MikeRalphson requested changes
LGTM apart from two tiny nits. Tested at https://spec.mermade.org.uk/

2023-03-02 15:24 UTC, MikeRalphson commented on registry/index.md
> +{% for registry in site.collections %}{% unless registry.hidden %}* <a href="..//api/{{ registry.slug }}.json">{{ registry.slug }}.json</a>{% endunless %}
```suggestion
{% for registry in site.collections %}{% unless registry.hidden %}* <a href="../api/{{ registry.slug }}.json">{{ registry.slug }}.json</a>{% endunless %}
```

2023-03-02 15:24 UTC, MikeRalphson commented on registry/index.md
> +* [feed.xml](./rss/feed.xml)
```suggestion
* [feed.xml](../rss/feed.xml)
```

2023-03-02 19:03 UTC, handrews commented
Thanks for the thorough testing @MikeRalphson — I committed both of your suggestions.

2023-03-02 19:11 UTC, MikeRalphson approved these changes
LGTM Thanks.

2023-03-03 15:31 UTC, merged

2023-03-03 15:31 UTC, whitlockjc commented
Thanks for everyone involved!