ciba-grant-3.2.0.md
OAI/OpenAPI-Specification pull request #3615
Opened 2024-02-29 20:14 UTC by shilpa-padgaonkar

Fixes #3587 

branch and file:
* 3.2.0 spec: v3.2.0-dev branch, versions/3.2.0.md

2024-03-21 09:54 UTC, LasneF commented
@shilpa-padgaonkar  : 

we should upgrade as well the schema 
https://github.com/OAI/OpenAPI-Specification/blob/v3.2.0-dev/schemas/v3.1/schema.yaml 

@handrews  this raise the point that the 3.2 should have its own schema version  (compatible but still its own version) 

to me the delivery mode should be an enum following the acceptable values
"backchannel_token_delivery_mode: REQUIRED. One of the following values: poll, ping, or push." 

about user code  , we may need to include it as part of the sample 
not sure if as well it should not be a boolean , not clear why a string array 

another point should it be called ciba , or should it be called backchannel as the OIDC spec mentionned those name as of parameter (ie it s just a legitimate question , to me ciba is fine as pointing the precise concept, not aware if there are other back channel technology leveraging those concept)

2024-03-21 16:31 UTC, darrelmiller commented
Could you help me understand why there is a need for a new OAuth2Flow when this information could be communicated via an OpenIDConnect configuration document considering it is an OIDC specific flow?

2024-03-22 12:42 UTC, AxelNennker commented
> Could you help me understand why there is a need for a new OAuth2Flow when this information could be communicated via an OpenIDConnect configuration document considering it is an OIDC specific flow?

Hi @darrelmiller although it sounds like "OpenID Connect Client-Initiated Backchannel Authentication Flow" is the same as OpenId Connect is is not.
Also an OpenId Provider can offer CIBA and Authorization Code flow and then the API consumer would not know if the API only allows CIBA (or is intended to be used with CIBA).

This idea of introducing ciba to OAI comes out of the Camara project where we discovered the need to specify this flow.
Many Camara APIs use CIBA. Many APIs from MobileConnect also use CIBA but the flow was communicated offline and not documented in the e.g. openapi.yaml. We found that the flow should be part of the Camara API specification, and here we are.
Hope this explains why we need this and why openIdConnectUrl is not enough.

2024-04-12 21:12 UTC, shilpa-padgaonkar commented
@LasneF : Thanks for your feedback.
- I have updated the schema files.
- fixed the type of ciba_user_code to boolean
- for ciba_delivery_modes, it is also possible that not just one, but rather 2 or all 3 of the delivery modes are selected.

2024-04-18 16:40 UTC, darrelmiller approved these changes

2024-04-18 16:43 UTC, darrelmiller commented on versions/3.2.0.md
> +<a name="backchannel_authentication_request_signing_alg_values"></a>ciba_signing_algs | Array[`string`] | `oauth2` (`"ciba"`) | **OPTIONAL**. JSON array containing a list of the JWS signing algorithm
```suggestion
<a name="backchannel_authentication_request_signing_alg_values"></a>ciba_signing_algs | Array[`string`] | `oauth2` (`"ciba"`) |  JSON array containing a list of the JWS signing algorithms (alg values) supported by the OP (OpenIdConnect Provider) for signed authentication requests
```

2024-04-18 16:44 UTC, darrelmiller commented on versions/3.2.0.md
> +<a name="backchannel_user_code_parameter_supported"></a>ciba_user_code | `boolean` | `oauth2` (`"ciba"`) | **OPTIONAL**. Boolean value specifying whether the OP supports the use of the user_code para
```suggestion
<a name="backchannel_user_code_parameter_supported"></a>ciba_user_code | `boolean` | `oauth2` (`"ciba"`) |  Boolean value specifying whether the OP supports the use of the user_code parameter, with true indicating support. If omitted, the default value is false.
```

2024-04-18 16:44 UTC, lornajane commented
Sorry, I know we've had some back-and-forth on the schemas, but since this change won't go into 3.1, it would be better to omit the schema updates from this pull request (the 3.2 schemas haven't been created yet), we can't merge this pull request with these schema changes in.

2024-04-18 16:46 UTC, darrelmiller commented on versions/3.2.0.md
> +<a name="backchannel_token_delivery_modes_supported"></a>ciba_delivery_modes | Array[`string`] | `oauth2` (`"ciba"`) | **REQUIRED**. JSON array containing one or more of the following values: poll, p
OpenAPI uses camelCasing for parameter values.  So although the CIBA specification uses snake case, for consistency we should require tooling to do the translation and maintain consistency in the OpenAPI description.

2024-04-18 16:47 UTC, darrelmiller requested changes
Remove OPTIONAL keywords and change casing of parameters

2024-04-18 17:14 UTC, handrews commented
@darrelmiller 

> Remove OPTIONAL keywords and change casing of parameters

I presume you meant "Remove OPTIONAL ***from*** keywords..." rather than removing the keywords marked OPTIONAL

2024-04-18 19:20 UTC, shilpa-padgaonkar commented on versions/3.2.0.md
> +<a name="backchannel_token_delivery_modes_supported"></a>ciba_delivery_modes | Array[`string`] | `oauth2` (`"ciba"`) | **REQUIRED**. JSON array containing one or more of the following values: poll, p
```suggestion
<a name="backchannelTokenDeliveryModesSupported"></a>ciba_delivery_modes | Array[`string`] | `oauth2` (`"ciba"`) | **REQUIRED**. JSON array containing one or more of the following values: poll, ping, and push.
```

2024-04-18 19:21 UTC, shilpa-padgaonkar commented on versions/3.2.0.md
> +<a name="backchannel_authentication_request_signing_alg_values"></a>ciba_signing_algs | Array[`string`] | `oauth2` (`"ciba"`) |  JSON array containing a list of the JWS signing algorithms (alg values
```suggestion
<a name="backchannelAuthenticationRequestSigningAlgValues"></a>ciba_signing_algs | Array[`string`] | `oauth2` (`"ciba"`) |  JSON array containing a list of the JWS signing algorithms (alg values) supported by the OP (OpenIdConnect Provider) for signed authentication requests
```

2024-04-18 19:22 UTC, shilpa-padgaonkar commented on versions/3.2.0.md
> +<a name="backchannel_user_code_parameter_supported"></a>ciba_user_code | `boolean` | `oauth2` (`"ciba"`) |  Boolean value specifying whether the OP supports the use of the user_code parameter, with t
```suggestion
<a name="backchannelUserCodeParameterSupported"></a>ciba_user_code | `boolean` | `oauth2` (`"ciba"`) |  Boolean value specifying whether the OP supports the use of the user_code parameter, with true indicating support. If omitted, the default value is false.
```

2024-04-18 19:24 UTC, shilpa-padgaonkar commented on versions/3.2.0.md
> +<a name="backchannelTokenDeliveryModesSupported"></a>ciba_delivery_modes | Array[`string`] | `oauth2` (`"ciba"`) | **REQUIRED**. JSON array containing one or more of the following values: poll, ping,
```suggestion
<a name="backchannelTokenDeliveryModesSupported"></a>cibaDeliveryModes | Array[`string`] | `oauth2` (`"ciba"`) | **REQUIRED**. JSON array containing one or more of the following values: poll, ping, and push.
```

2024-04-18 19:26 UTC, shilpa-padgaonkar commented on versions/3.2.0.md
> +<a name="backchannelAuthenticationRequestSigningAlgValues"></a>ciba_signing_algs | Array[`string`] | `oauth2` (`"ciba"`) |  JSON array containing a list of the JWS signing algorithms (alg values) sup
```suggestion
<a name="backchannelAuthenticationRequestSigningAlgValues"></a>cibaSigningAlgs | Array[`string`] | `oauth2` (`"ciba"`) |  JSON array containing a list of the JWS signing algorithms (alg values) supported by the OP (OpenIdConnect Provider) for signed authentication requests
```

2024-04-18 19:26 UTC, shilpa-padgaonkar commented on versions/3.2.0.md
> +<a name="backchannelUserCodeParameterSupported"></a>ciba_user_code | `boolean` | `oauth2` (`"ciba"`) |  Boolean value specifying whether the OP supports the use of the user_code parameter, with true
```suggestion
<a name="backchannelUserCodeParameterSupported"></a>cibaUserCode | `boolean` | `oauth2` (`"ciba"`) |  Boolean value specifying whether the OP supports the use of the user_code parameter, with true indicating support. If omitted, the default value is false.
```

2024-04-18 19:30 UTC, shilpa-padgaonkar commented on versions/3.2.0.md
> +      "ciba_delivery_modes": ["poll"]
```suggestion
      "cibaDeliveryModes": ["poll"]
```

2024-04-19 13:30 UTC, shilpa-padgaonkar commented
> Sorry, I know we've had some back-and-forth on the schemas, but since this change won't go into 3.1, it would be better to omit the schema updates from this pull request (the 3.2 schemas haven't been created yet), we can't merge this pull request with these schema changes in.

@lornajane Reverted schema changes

2024-04-19 13:30 UTC, shilpa-padgaonkar commented
@darrelmiller Done changes for camelCase. Kindly check.

2024-04-25 16:00 UTC, ralfhandl commented on versions/3.2.0.md
> +<a name="backchannelTokenDeliveryModesSupported"></a>cibaDeliveryModes | Array[`string`] | `oauth2` (`"ciba"`) | **REQUIRED**. JSON array containing one or more of the following values: poll, ping, a
```suggestion
<a name="backchannelTokenDeliveryModesSupported"></a>cibaDeliveryModes | Array[`string`] | `oauth2` (`"ciba"`) | **REQUIRED**. JSON array containing one or more of the following values: `poll`, `ping`, and `push`.
```

2024-04-25 16:39 UTC, ralfhandl approved these changes

2024-04-25 16:40 UTC, lornajane approved these changes
Thank you for being patient with us and working through the amendments.

2024-04-25 16:41 UTC, merged