Explain dynamic refs for generics (3.2.0 port of )
OAI/OpenAPI-Specification pull request #3795
Opened 2024-05-09 19:44 UTC by handrews

* Ports #3714 
* Fixes #3601 

Includes an example.  This intentionally does not explain how dynamic referencing works, as there are better resources available in both the spec and (more readably) the official JSON Schema blog.

2024-05-14 08:44 UTC, lornajane submitted a review, later dismissed
An example always helps :) Thanks!

2024-05-14 08:52 UTC, ralfhandl requested changes
- Align YAML with JSON example
- Use consistent YAML formatting identical to #3714

2024-05-14 08:52 UTC, ralfhandl commented on versions/3.2.0.md
> +    genericArray:
```suggestion
    genericArrayComponent:
```

2024-05-14 08:52 UTC, ralfhandl commented on versions/3.2.0.md
> +      required: [dataType, data]
```suggestion
      required: 
      - dataType 
      - data
```

2024-05-14 08:52 UTC, ralfhandl commented on versions/3.2.0.md
> +          enum: [string, number]
```suggestion
          enum:
          - string
          - number
```

2024-05-14 08:52 UTC, ralfhandl commented on versions/3.2.0.md
> +          data: {$ref: array_of_strings}
```suggestion
          dataType:
            const: string
          data:
            $ref: array_of_strings
```

2024-05-14 08:52 UTC, ralfhandl commented on versions/3.2.0.md
> +          data: {$ref: array_of_numbers}
```suggestion
          dataType:
            const: number
          data:
            $ref: array_of_numbers
```

2024-05-14 15:33 UTC, handrews commented
@ralfhandl ah, I see what happened here - I auto-ported the fix with `git format-patch` and `git am`, but spliced off some (but not all) of the during-review commits.  I will rebase and re-port this so that we get the exact same fixes.

2024-05-14 15:36 UTC, handrews commented
@ralfhandl I've marked your suggestions as resolved as the rebased force-push I just did _should_ contain all of your corrections from the previous PR (as well as some from other folks).

2024-05-15 08:33 UTC, ralfhandl approved these changes

2024-05-16 16:08 UTC, handrews commented
This had two approvals and the minor fix cleared them - one re-approval from the person who asked for the minor fix is sufficient, so I'll merge this (it's a port, after all).

2024-05-16 16:08 UTC, merged