[new] scripts/update-schema-latest.sh
OAI/OpenAPI-Specification pull request #3815
Opened 2024-05-17 06:04 UTC by TakahikoKawasaki

This script does the following.

1. Switch to the 'gh-pages' branch.

2. Copy "schemas/v{major}.{minor}/schema.json" in the 'main' branch to "oas/{major}.{minor}/schema/{YYYY-MM-DD}" in the 'gh-pages' branch. The value of {YYYY-MM-DD} is extracted from the '$id' property in the schema.json file.

3. Create a symbolic link "latest" under "oas/{major}.{minor}/schema" that points to the "{YYYY-MM-DD}" file.

4. Copy "schemas/v{major}.{minor}/schema-base.json" in the 'main' branch to "oas/{major}.{minor}/schema-base/{YYYY-MM-DD}" in the 'gh-pages' branch. The value of {YYYY-MM-DD} is extracted from the '$id' property in the schema-base.json file.

5. Create a symbolic link "latest" under "oas/{major}.{minor}/schema-base" that points to the "{YYYY-MM-DD}" file.

2024-05-17 14:11 UTC, ralfhandl requested changes
Wrong PR 🙄

2024-05-24 07:42 UTC, ralfhandl commented
Hi @TakahikoKawasaki,

Thanks for providing the script. 

The script works fine for the v3.1 case with separate `schema` and `schema-base`, and fail for the v3.0 case where there is only `schema`.

Would you mind adding this distinction to the scripts?

Thanks in advance!

2024-06-10 00:22 UTC, TakahikoKawasaki commented
@ralfhandl
- Updated the script to support the version 3.0.
- Versions older than 3.0 are rejected on the assumption that maintenance of 2.x and older versions has stopped.

If it is necessary to support versions older than 3.0, please let me know.

2024-08-23 11:51 UTC, ralfhandl commented on scripts/update-schema-latest.sh
> +    __execute_command "${link_command}"
If #4034 is approved, this needs to become

```suggestion
    # The commands to update the 'latest' file.
    link_command="cd ${dst_dir} && ln -sf ${date} latest"
    link_command2="cd ${dst_dir} && ln -sf ${date} latest.json"

    # Execute the commands.
    __execute_command "${copy_command}"
    __execute_command "${link_command}"
    __execute_command "${link_command2}"
```

2024-09-19 00:57 UTC, limck5856 approved these changes

2024-10-14 12:30 UTC, ralfhandl commented
Steps 3 and 5 (symlink `latest`) need to be replaced with
* rename `{YYYY-MM-DD}.md` to match the date of the new schema file

2024-10-14 12:31 UTC, ralfhandl requested changes
Steps 3 and 5 (symlink `latest`) need to be replaced with
* rename `{YYYY-MM-DD}.md` to match the date of the new schema file

2024-10-31 17:00 UTC, lornajane commented
I'm closing this pull request since it's no longer needed since the recent changes to the schema publishing process.

2024-10-31 17:00 UTC, closed without merging