3.2.0 markdown updates
OAI/OpenAPI-Specification pull request #4025
Opened 2024-08-15 12:09 UTC by ralfhandl

3.2.0 port of
* #3991

2024-08-22 13:48 UTC, mikekistler approved these changes
Looks good! 👍

2024-08-28 17:32 UTC, handrews requested changes
I'm confused as to what happens in which PR, so I'm just going to say the same thing on this one:


@ralfhandl can you re-do this with the tables not expanded since we agreed on that for the other branches? That will keep the change history so much less polluted on this branch.

Ideally I'd prefer not collapsing the spaces after periods, but I'm not going to my heels in on it (but it does create more noise and makes it harder to find sentence changes in a fixed-width editor).

2024-08-28 18:13 UTC, ralfhandl commented
The "table condenser" is currently only in #4040. @mikekistler has approved it half a dozen times already, and I'd happily merge it and port it to 3.1.1 and 3.2.0 with a second approval.

2024-08-28 20:33 UTC, ralfhandl commented
This is the first part of several PRs to sync 3.2.0 with 3.1.1
* #4025 - remove TOC, prettier, markdownlint
* #4026 - stylistic harmonization
* #4035 - property, field, keyword cleanup

We can merge them one by one, thus minimizing the differences, or just merge the last one with the cumulative changes and close the others.

We'll need an additional diff to 3.1.1 to add the changes we did since the last of these PRs was created.

2024-08-29 20:58 UTC, handrews approved these changes

2024-08-29 20:58 UTC, handrews commented on versions/3.2.0.md
> +```js
This isn't exactly accurate but looks nicer than plain text so OK :-)

2024-08-29 21:53 UTC, ralfhandl commented
Merging as @mikekistler has approved before table condensing.

2024-08-29 21:53 UTC, merged