v3.0.4(schema): Update empty security array constraint
OAI/OpenAPI-Specification pull request #4069
Opened 2024-09-04 20:43 UTC by jeremyfiel

based on discussions

*  https://github.com/OAI/OpenAPI-Specification/issues/3938#issuecomment-2308874884

* https://github.com/OAI/OpenAPI-Specification/pull/4007

2024-09-04 22:37 UTC, handrews commented
@jeremyfiel could you please re-target this to main?  We don't change the schemas on the branches (except by accident)

2024-09-04 22:46 UTC, jeremyfiel commented
Oof.  Changing requires a new force push.  I'll do it later today when I get a chance

2024-09-05 10:04 UTC, ralfhandl commented
@jeremyfiel Thanks for providing this!

Assuming this PR is to be merged _after_ publication of 3.0.4 I've converted it to draft.

2024-09-05 10:05 UTC, ralfhandl requested changes
Why does this PR contain files except the schema.yaml?

Is it supposed to be merged after publication of 3.0.4?

Convertin

2024-09-05 10:05 UTC, ralfhandl commented on schemas/v3.0/schema.yaml
> +    minItems: 1
This contradicts what we say now in the spec

2024-09-05 16:40 UTC, handrews commented
Closing for the same reasons that @lornajane articulated on the 3.1.1 version of this (although we look forward to incorporating this sort of idea in a different form in the future!):

> There are some problems with this pull request, but having discussed the proposed change (the newest commit), this isn't a useful change to make to our existing validation schemas since it is valid to have an empty security array. Please keep an eye on the project for more discussion about linting schemas in addition to our validation schemas.

2024-09-05 16:40 UTC, closed without merging