Fix Document vs Description terminology (3.1.1, port of #4100)
OAI/OpenAPI-Specification pull request #4131
Opened 2024-10-10 20:09 UTC by handrews

I think this is correct (and includes the last remaining "suggestion" about the Server Object `url` field wording), but please review carefully.  I still need to re-review it myself, as resolving conflicts and adjusting for 3.1.1 was a bit complex in spots.

Note that #4130 does not need to be ported as it is already handled by having the two distinct "Relative References in..." (URI vs URL) sections.  Although those sections assume the split documented in #4130 that we said was ambiguous in 3.0.

2024-10-11 08:00 UTC, ralfhandl requested changes
The same three nits as in #4100

2024-10-11 18:51 UTC, handrews commented on versions/3.1.1.md
I'm guessing this is the Server Object bit- let's see what wording we settle on in 3.0.4 before updating here.

2024-10-12 23:48 UTC, handrews commented on versions/3.1.1.md
@ralfhandl I've updated this with the text @mikekistler accepted in the 3.0.4 PR, so I'm going to mark this resolved.

2024-10-14 08:27 UTC, ralfhandl approved these changes

2024-10-14 13:16 UTC, mikekistler approved these changes
Looks good! 👍

2024-10-14 14:02 UTC, merged