Add dark mode support to the HTML versions of the OpenAPI specs
OAI/OpenAPI-Specification pull request #4268
Opened 2024-12-19 07:06 UTC by Bellangelo

Closes https://github.com/OAI/OpenAPI-Specification/issues/3866

Except from adding the necessary CSS rules I have also moved it into its own file here: https://github.com/OAI/OpenAPI-Specification/commit/b3949bdf468dbdf565d0854a9abef8c6bbdcbd88

This declutters a little bit the `md2html.js`. Plus, we can also use the IDE for styling and formatting.

The CSS is heavily inspired by the work of @pavelkornev, see https://github.com/OAI/OpenAPI-Specification/issues/3866#issuecomment-2327406991

End results: https://jsfiddle.net/gu23x9kb/

2024-12-19 09:59 UTC, ralfhandl requested changes
As @pavelkornev points out in https://github.com/OAI/OpenAPI-Specification/issues/3866#issuecomment-2553095801 this only works on my Mac if the system appearance is set to Dark. If it is set to Light, or set to Auto and is currently Light, then the switch doesn't work.

2024-12-19 11:29 UTC, Bellangelo commented
> As @pavelkornev points out in [#3866 (comment)](https://github.com/OAI/OpenAPI-Specification/issues/3866#issuecomment-2553095801) this only works on my Mac if the system appearance is set to Dark. If it is set to Light, or set to Auto and is currently Light, then the switch doesn't work.

@ralfhandl Oh yes... I had encapsulated the code under the `prefers-color-scheme` which was running only on dark mode. Fixed in https://github.com/OAI/OpenAPI-Specification/pull/4268/commits/973999a6a7c1e774b72ca44aa24cf53d4647f782

2024-12-19 13:35 UTC, ralfhandl commented
Still doesn't work if system is in Light mode:
![image](https://github.com/user-attachments/assets/c0916ac3-1d98-41c6-a1a9-91451d0a6e03)

and
![image](https://github.com/user-attachments/assets/5f3d4e42-2fc6-4ecf-8b96-c602e5f0b9c6)

Background stays white, only text colors change.

2024-12-19 13:37 UTC, ralfhandl requested changes
On MacOS only works if system is in dark mode.

2024-12-19 14:18 UTC, Bellangelo commented
> On MacOS only works if system is in dark mode.

@ralfhandl That's weird.. I am not getting the same results as you. I am testing it on a MacOS and it perfectly works with Firefox and Safari. Could it be a browser setting? I will further look into it.

2024-12-19 15:19 UTC, Bellangelo commented
@ralfhandl I have managed to reproduce it with Firefox. The problem is that respec adds this link
```html
<link rel="stylesheet" media="(prefers-color-scheme: dark)" href="https://www.w3.org/StyleSheets/TR/2021/dark.css">
```
Once again, due to the `(prefers-color-scheme: dark)` it doesn't work correctly. For this reason, i have copied/pasted the changes from the file into our `main.css` here: https://github.com/OAI/OpenAPI-Specification/pull/4268/commits/e25d7530c2a6a5d7c5397b6da4cdb93758e98076

Although, this seems to be fixing the issue it still loads unnecessarily the `dark.css`. Would it be ok if I changed the `build.sh`to parse the output and remove it? Or are we ok with the extra request?

**Note:** I will fix the tests after we agree on the solution.

2024-12-19 16:15 UTC, ralfhandl commented
> i have copied/pasted the changes from the file into our `main.css`

Is that necessary? I'd prefer to keep our CSS as slim as possible.

2024-12-19 16:16 UTC, ralfhandl commented
> Would it be ok if I changed the `build.sh`to parse the output and remove it?

Why not, if that works better?

2024-12-19 17:49 UTC, lornajane commented
@swaldron58 can you check if our theme fits this?

2024-12-20 23:04 UTC, Bellangelo commented
> Is that necessary? I'd prefer to keep our CSS as slim as possible.
@ralfhandl I think so. The implementation depends on how Respec handles dark mode, which is by adding the `darkmode` class in the `body` tag. Since we apply the styling based on this class and not by checking the preferred mode the `media="(prefers-color-scheme: dark)"` becomes an obstacle.

> Why not, if that works better?
@ralfhandl I have changed the `build.sh` in this [commit](https://github.com/OAI/OpenAPI-Specification/pull/4268/commits/d5f765eaa96f2bd367e6d583cb66cbbdd42bcbfe) and its tests [here](https://github.com/OAI/OpenAPI-Specification/pull/4268/commits/ffa5176bc27e721624a43430fad3f0378799063e).

2025-01-03 09:27 UTC, ralfhandl commented
@Bellangelo Thanks for the detailed analysis!

> It seems that we cannot stop the loading of the `dark.css` without changing quite a few things.

I'd prefer not to go that path, given how fiddly it was to get back from a modified ReSpec v21 to an unmodified ReSpec v35.

How far can we get with just additional CSS?

2025-01-03 17:55 UTC, Bellangelo commented
> How far can we get with just additional CSS?

@ralfhandl What exactly do you mean? The dark mode should be working right now.

2025-01-23 18:00 UTC, lornajane commented
To clarify, we don't want any customisation on respec itself, we will use the published version of that library. @ralfhandl 's question is whether we can achieve dark mode purely with CSS styles?

2025-02-05 13:52 UTC, ralfhandl approved these changes
Works fine in Chrome and Firefox on Windows. Preview:
* https://ralfhandl.github.io/OpenAPI-Specification/oas/v3.1.1.html

2025-02-06 12:54 UTC, mikekistler approved these changes
I'm not qualified to review the actual code changes, but I tested this on my Mac in both Safari and Chrome and it works great.

2025-02-06 17:42 UTC, merged