Editorial change: fix anchor to Components.securitySchemes
OAI/OpenAPI-Specification pull request #4282
Opened 2024-12-27 14:01 UTC by char0n

The `anchor` is pointing to `Security Scheme Object` definition instead of `Components.securitySchemes`

2025-01-02 11:15 UTC, ralfhandl requested changes
@char0n Thanks for catching this unintended duplicate anchor!

Unfortunately this means that some of the references to this anchor need to be changed to still point here, most likely all except the ones in this line.

2025-01-03 11:56 UTC, char0n commented
@ralfhandl thanks. Amended all appropriate references.

2025-01-05 08:43 UTC, Facebook575 approved these changes

2025-01-05 08:46 UTC, Facebook575 approved these changes

2025-01-05 17:55 UTC, handrews approved these changes

2025-01-10 14:57 UTC, ralfhandl approved these changes

2025-01-10 14:58 UTC, merged